server:
  port: 8091 # La puerta única de entrada a todo Eco-Ride

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. Usuarios
        - id: ms-usuario
          uri: lb://MS-USUARIO
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/usuarios/(?<segment>.*)
                replacement: /api/usuarios/${segment}

        # 2. Perfiles
        - id: ms-perfiles
          uri: lb://MS-PERFILES
          predicates:
            - Path=/api/v1/perfiles/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/perfiles/(?<segment>.*)
                replacement: /api/perfiles/${segment}

        # 3. Vehículos
        - id: ms-vehiculos
          uri: lb://MS-VEHICULOS
          predicates:
            - Path=/api/v1/vehiculos/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/vehiculos/(?<segment>.*)
                replacement: /api/vehiculos/${segment}

        # 4. Geolocalización
        - id: ms-geolocalizacion
          uri: lb://MS-GEOLOCALIZACION
          predicates:
            - Path=/api/v1/geolocalizacion/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/geolocalizacion/(?<segment>.*)
                replacement: /api/geolocalizacion/${segment}

        # 5. Viajes
        - id: ms-viajes
          uri: lb://MS-VIAJES
          predicates:
            - Path=/api/v1/viajes/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/viajes/(?<segment>.*)
                replacement: /api/viajes/${segment}

        # 6. Precio
        - id: ms-precio
          uri: lb://MS-PRECIO
          predicates:
            - Path=/api/v1/precios/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/precios/(?<segment>.*)
                replacement: /api/precios/${segment}

        # 7. Pago
        - id: ms-pago
          uri: lb://MS-PAGO
          predicates:
            - Path=/api/v1/pagos/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/pagos/(?<segment>.*)
                replacement: /api/pagos/${segment}

        # 8. Notificaciones
        - id: ms-notificaciones
          uri: lb://MS-NOTIFICACIONES
          predicates:
            - Path=/api/v1/notificaciones/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/notificaciones/(?<segment>.*)
                replacement: /api/notificaciones/${segment}

        # 9. Calificaciones
        - id: ms-calificaciones
          uri: lb://MS-CALIFICACIONES
          predicates:
            - Path=/api/v1/calificaciones/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/calificaciones/(?<segment>.*)
                replacement: /api/calificaciones/${segment}

        # 10. Mantenimiento
        - id: ms-mantenimiento
          uri: lb://MS-MANTENIMIENTO
          predicates:
            - Path=/api/v1/mantenimiento/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/mantenimiento/(?<segment>.*)
                replacement: /api/mantenimiento/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG