server:
  port: 8088

spring:
  application:
    name: ms-notificaciones
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/ecoride_notificaciones
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
